shopkotler/authapp/urls.py
from django.urls import path
import authapp.views as authapp


app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

shopkotler/shopkotler/urls.py
from django.contrib import admin
from django.urls import path, include
# from mainapp import urls
from . import views
from django.conf import settings
from  django.conf.urls.static import static
from authapp import urls as authapp_urls
# import mainapp
from mainapp import urls as mainapp_urls
from adminapp import urls as adminapp_urls
from basketapp import urls as basketapp_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_staff/', include(adminapp_urls, namespace='admin_staff'), name='admin_staff'),
    path('admin_categories/', include(adminapp_urls, namespace='admin_categories'), name='admin_categories'),
    path('admin_products/', include(adminapp_urls, namespace='admin_products'), name='admin_products'),

    path('auth/', include(authapp_urls, namespace='auth'), name='auth'),
    path('products/', include(mainapp_urls, namespace='products'), name='products'),
    path('basket/', include(basketapp_urls, namespace='basket'), name='basket'),
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopkotler/authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class ShopUser(AbstractUser):
    avatar = models.ImageField(upload_to='user_avatars', blank=True)
    age = models.PositiveIntegerField(verbose_name='возраст')

    is_delete = models.BooleanField(default=False)

shopkotler/authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms
from .models import ShopUser


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form=control'


class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'password1', 'password2', 'email', 'age', 'avatar')

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field_name, field in self.fields.items():
                field.widget.attrs['class'] = 'form-control'
                field.help_text = ''

        def clean_age(self):
            data = self.cleaned_data['age']
            if data < 18:
                raise forms.ValidationError('Вы слишком молоды')

            return data


class ShopUserEditForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'email', 'age', 'avatar', 'password')

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field_name, field in self.fields.items():
                field.widget.attrs['class'] = 'form-control'
                field.help_text = ''
                if field_name == 'password':
                    field.widget = forms.HiddenInput()

        def clean_age(self):
            data = self.cleaned_data['age']
            if data < 18:
                raise forms.ValidationError('Вы слишком молоды')

            return data

shopkotler/authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth
from django.urls import reverse
from authapp.forms import ShopUserLoginForm, ShopUserRegisterForm, ShopUserEditForm


def login(request):
    title = 'вход'

    login_form = ShopUserLoginForm(data=request.POST)  # отсылается когда заполняем форму, приходит в виде словаря
    next = request.GET['next'] if 'next' in request.GET.keys() else ''

    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        passsword = request.POST['password']

        user = auth.authenticate(username=username, password=passsword) # может password
        if user and user.is_active:
            auth.login(request, user)
            if 'next' in request.POST.keys():
                return HttpResponseRedirect(request.POST['next'])
            else:
                return HttpResponseRedirect(reverse('index'))

    context = {
        'title': title,
        'login_form': login_form,
        'next': next,
    }

    return render(request, 'authapp/login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    title = 'регистрация'

    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        register_form = ShopUserRegisterForm()

    context = {'title': title, 'register_form': register_form}

    return render(request, 'authapp/register.html', context)


def edit(request):
    title = 'редактирование'

    if request.method == 'POST':
        edit_form = ShopUserEditForm(request.POST, request.FILES, instance=request.user)

        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:edit'))
    else:
        edit_form = ShopUserEditForm(instance=request.user)

    context = {'title': title, 'edit_form': edit_form}

    return render(request, 'authapp/edit.html', context)

shopkotler/authapp/templates/authapp/base.html
<!DOCTYPE html>

{% load static %}

<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static '/style.css' %}">
        <link rel="stylesheet" href="{% static '/fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}

    {% endblock %}
</head>
<body>
    <div class="w-50 ml-3">
    <div class="container">
        <div class="login">
            <div class="h2 text-center head">
                Профиль пользователя
            </div>

            {% block content %}

            {% endblock %}
        </div>
    </div>
    </div>
</body>
</html>

shopkotler/authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block content %}
    <div class="col-4 mx-auto">
        <div class="row">
            <div class="user_avatar">
                <img src="/media/{{ user.avatar }}" class="rounded-circle">
            </div>
        </div>
    <div class="row">
        <form class="form_horizontal" action="{% url 'auth:edit' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ edit_form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <button class="btn btn-round form-control last">
            <a href="{% url 'index' %}" class="">
                на главную
            </a>
        </button>
    </div>
    </div>
{% endblock %}

shopkotler/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block content %}
<div class="w-50 ml-3">
    <form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
        {% csrf_token %}
        {{ login_form.as_p }}

        <br>
        {% if next %}
            <input type="hidden" name="next" value="{{ next }}">
        {% endif %}
        <input class="form-control btn btn-primary" type="submit" value="войти">
    </form>

    <button class="btn btn-round form-control">
        <a href="{% url 'auth:register' %}" class="">
            зарегистрироваться
        </a>
    </button>
</div>

{% endblock %}

shopkotler/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block content %}
    <div class="col-3 mx-auto">
    <form class="form_horizontal" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ register_form.as_p }}
        <input class="form-control" type="submit" value="зарегистрироваться">
    </form>
    </div>

{% endblock %}