shopkotler/adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp
app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UserListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),

    path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.ProductsListView.as_view(), name='products'),
    path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
]

shopkotler/authapp/urls.py
from django.urls import path
import authapp.views as authapp


app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

shopkotler/basketapp/urls.py
from django.urls import path
import basketapp.views as basket


app_name = 'basketapp'


urlpatterns = [
    path('', basket.basket, name='view'),
    path('add/<int:pk>/', basket.basket_add, name='add'),
    path('remove/<int:pk>/', basket.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket.basket_edit, name='edit'),
]

shopkotler/shopkotler/urls.py
from django.contrib import admin
from django.urls import path, include
# from mainapp import urls
from . import views
from django.conf import settings
from  django.conf.urls.static import static
from authapp import urls as authapp_urls
# import mainapp
from mainapp import urls as mainapp_urls
from adminapp import urls as adminapp_urls
from basketapp import urls as basketapp_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_staff/', include(adminapp_urls, namespace='admin_staff'), name='admin_staff'),
    path('admin_categories/', include(adminapp_urls, namespace='admin_categories'), name='admin_categories'),
    path('admin_products/', include(adminapp_urls, namespace='admin_products'), name='admin_products'),

    path('auth/', include(authapp_urls, namespace='auth'), name='auth'),
    path('products/', include(mainapp_urls, namespace='products'), name='products'),
    path('basket/', include(basketapp_urls, namespace='basket'), name='basket'),
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopkotler/shopkotler/views.py
from django.shortcuts import render

from basketapp.models import Basket
from mainapp.models import Product


def index(request):
    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)

    title = 'shopkotler'
    products = Product.objects.all()[:4]

    context = {
        'products': products,
        'some_name': 'современные',
        'title': title,
        'basket': basket,

    }
    return render(request, 'shopkotler/index.html', context=context)


def contact(request):
    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)

    title = 'контакты'

    context = {
        'title': title,
        'basket': basket,
    }

    return render(request, 'shopkotler/contact.html', context=context)

shopkotler/shopkotler/templates/shopkotler/includes/inc_contact_menu.html
<div class="header clearfix">
    <a href="index.html" class="logo"></a>
    <ul class="menu">
        <li><a href="{% url 'index' %}">домой</a></li>
        <li><a href="{% url 'products:products' %}">продукты</a></li>
        <li><a href="{% url 'contact' %}" class="active">контакты</a></li>
        {% if user.is_authenticated %}
        <li>
            <a href="{% url 'auth:edit' %}">
            {{ user.first_name|default:'Пользователь' }}
            </a>
        </li>
        {% endif %}
        <li>
            {% if user.is_authenticated %}
                <a href="{% url 'auth:logout' %}">выйти</a>
            {% else %}
                <a href="{% url 'auth:login' %}">войти</a>
            {% endif %}
        </li>
    </ul>
    <div class="col-3">
    <a href="#" class="search"></a>
        {% if basket %}
        <a href="{% url 'basket:view' %}" class="fa fa-shopping-basket">
            <span>
                {{ basket.0.total_cost|floatformat:0 }} руб.
                {{ basket.0.total_quantity }} шт.
            </span>
        </a>
        {% endif %}
    </div>
</div>

shopkotler/shopkotler/templates/shopkotler/includes/inc_footer.html
<div class="footer">
    <div class="clearfix">
        <div class="text-footer">
            <h3>контакты</h3>
        </div>
        <div class="text-footer">
            <h3>полезная информация</h3>
        </div>
        <div class="text-footer clearfix">
            <h3>Оставайтесь на связи</h3>
            <p>Подписаться на новости и рассылки</p>
            <form>
                <input type="email" name="email" placeholder="ваш email">
                <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
            </form>
        </div>
    </div>
    <p class="small">&copy; {% now "Y" %}</p>
    <div class="social">
        <a href="#" class="social1"></a>
        <a href="#" class="social2"></a>
        <a href="#" class="social3"></a>
        <a href="#" class="social4"></a>
    </div>
    <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
</div>

shopkotler/shopkotler/templates/shopkotler/includes/inc_main_menu.html
<div class="header clearfix">
    <div>
    <a href="{% url 'index' %}" class="logo"></a>
    </div>
    <div class="col-8">
    <ul class="menu">
        <li><a href="{% url 'index' %}" class="active">домой</a></li>
        <li><a href="{% url 'products:products' %}">продукты</a></li>
        <li><a href="{% url 'contact' %}">контакты</a></li>
        {% if user.is_authenticated %}
        <li>
            <a href="{% url 'auth:edit' %}">
            {{ user.first_name|default:'Пользователь' }}
            </a>
        </li>
        {% endif %}
        {% if user.is_superuser %}
        <li>
            <a href="{% url 'admin_staff:users' %}">Админка</a>
        </li>
        {% endif %}
        <li>
            {% if user.is_authenticated %}
                <a href="{% url 'auth:logout' %}">выйти</a>
            {% else %}
                <a href="{% url 'auth:login' %}">войти</a>
            {% endif %}
        </li>
    </ul>
    </div>
    <div class="col-3">
    <a href="#" class="search"></a>
        {% if basket %}
        <a href="{% url 'basket:view' %}" class="fa fa-shopping-basket">
            <span>
                {{ basket.0.total_cost|floatformat:0 }} руб.
                {{ basket.0.total_quantity }} шт.
            </span>
        </a>
        {% endif %}
    </div>
</div>

shopkotler/shopkotler/templates/shopkotler/includes/inc_products_menu.html
<div class="hero-white">
    <div class="header clearfix">
        <a href="index.html" class="logo"></a>
        <ul class="menu">
            <li><a href="{% url 'index' %}">домой</a></li>
            <li><a href="{% url 'products:products' %}" class="active">продукты</a></li>
            <li><a href="{% url 'contact' %}">контакты</a></li>
            {% if user.is_authenticated %}
            <li>
                <a href="{% url 'auth:edit' %}">
                {{ user.first_name|default:'Пользователь' }}
                </a>
            </li>
            {% endif %}
            <li>
            {% if user.is_authenticated %}
                <a href="{% url 'auth:logout' %}">выйти</a>
            {% else %}
                <a href="{% url 'auth:login' %}">войти</a>
            {% endif %}
            </li>

        </ul>
    <div class="col-3">
    <a href="#" class="search"></a>
        {% if basket %}
        <a href="{% url 'basket:view' %}" class="fa fa-shopping-basket">
            <span>
                {{ basket.0.total_cost|floatformat:0 }} руб.
                {{ basket.0.total_quantity }} шт.
            </span>
        </a>
        {% endif %}
    </div>
    </div>
</div>