shopkotler/authapp/urls.py
from django.urls import path
import authapp.views as authapp


app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
]

shopkotler/basketapp/urls.py
from django.urls import path
import basketapp.views as basket


app_name = 'basketapp'


urlpatterns = [
    path('', basket.basket, name='view'),
    path('add/<int:pk>/', basket.basket_add, name='add'),
    path('remove/<int:pk>/', basket.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket.basket_edit, name='edit'),
]

shopkotler/mainapp/urls.py
from django.urls import path
from .views import products


app_name = 'mainapp'


urlpatterns = [
    path('', products, name='products'),
    path('category/<int:pk>/', products, name='category'),
    path('category/<int:pk>/page/<int:page>/', products, name='page'),
]

shopkotler/shopkotler/urls.py
from django.contrib import admin
from django.urls import path, include
# from mainapp import urls
from . import views
from django.conf import settings
from  django.conf.urls.static import static
from authapp import urls as authapp_urls
# import mainapp
from mainapp import urls as mainapp_urls
from adminapp import urls as adminapp_urls
from basketapp import urls as basketapp_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_staff/', include(adminapp_urls, namespace='admin_staff'), name='admin_staff'),
    path('admin_categories/', include(adminapp_urls, namespace='admin_categories'), name='admin_categories'),
    path('admin_products/', include(adminapp_urls, namespace='admin_products'), name='admin_products'),

    path('auth/', include(authapp_urls, namespace='auth'), name='auth'),
    path('products/', include(mainapp_urls, namespace='products'), name='products'),
    path('basket/', include(basketapp_urls, namespace='basket'), name='basket'),
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopkotler/mainapp/models.py
from django.db import models

# blank=True - позволяет оставлять поле незаполненным, null=True ставит null в то поле которое не заполнено, но должно.


class ProductCategory(models.Model):
    name = models.CharField(
        verbose_name='имя',
        max_length=64,
        unique=True,
    )

    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )

    created = models.DateTimeField(
        auto_now_add=True,
    )

    updated = models.DateTimeField(
        auto_now=True,
    )

    is_delete = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.name} - {self.id} -- {self.created}'

    class Meta: # для изменения названий
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

# decimal = models.DecimalField(max_digits=10, decimal_places=223) - используется для финансовых записей
# python manage.py makemigrations - пишем в терминале - передача(миграция) для базы
# python manage.py migrate - для применения файла


class Product(models.Model):
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE,
        verbose_name='категория',
    )

    name = models.CharField(
        verbose_name='имя продукта',
        max_length=128,
    )

    image = models.ImageField(
        upload_to='products_images',
        blank=True,
        verbose_name='фото товара'
    )

    short_desc = models.CharField(
        verbose_name='краткое описание товара',
        max_length=60,
        blank=True,
    )

    description = models.TextField(
        verbose_name='описание продукта',
        blank=True,
    )

    price = models.DecimalField(
        verbose_name='цена продукта',
        max_digits=8,
        decimal_places=2,
        default=0,
    )

    quantity = models.PositiveIntegerField(
        verbose_name='количество на складе',
        default=0,
    )

    created = models.DateTimeField(
        auto_now_add=True,
    )

    updated = models.DateTimeField(
        auto_now=True,
    )

    is_delete = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.name} - {self.id} -- {self.created}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

shopkotler/mainapp/views.py
from django.shortcuts import render, get_object_or_404

from basketapp.models import Basket
from .models import Product, ProductCategory
import random

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def get_hot_product():
    products = Product.objects.all()

    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]

    return same_products


def products(request, pk=None, page=1):
    title = 'продукты'

    categories = ProductCategory.objects.all()
    basket = get_basket(request.user)

    if pk is not None:
        if pk == 0:
            products = Product.objects.all().order_by('price')
            category = {
                'pk': 0,
                'name': 'все'
            }
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category_id__pk=pk).order_by('price')

        paginator = Paginator(products, 2)

        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        hot_product = get_hot_product()
        same_products = get_same_products(hot_product)

        context = {
            'title': title,
            'categories': categories,
            'category': category,
            'products': products_paginator,
            'basket': basket,
            'hot_product': hot_product,
            'same_products': same_products,
        }

        return render(request, 'mainapp/products.html', context=context)


def product(request, pk):
    title = 'страница продута'
    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)
    context = {
        'title': title,
        'categories': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
        'basket': get_basket(request.user),
        'hot_product': hot_product,
        'same_products': same_products,
    }

    return render(request, 'mainapp/product.html', context)

shopkotler/mainapp/templates/mainapp/product.html
{% extends 'shopkotler/base.html' %}
{% load static %}

{% block style %}
	<link rel="stylesheet" type="text/css" href="{% static '/mainapp/style.css' %}">
{% endblock %}

{% block content %}
	{% include 'shopkotler/includes/inc_products_menu.html' %}
      <div class="details">
         <div class="links clearfix">
                <ul class="links-menu">
					<li>
						<a href="{% url 'products:category' 0 %}"
						   class="{% if request.resolver_match.kwargs.pk == '0' %}
									active
								  {% endif %}">
							все
						</a>

					</li>
					{% for link in categories %}
						<li>
							<a href="{% url 'products:category' link.pk %}"
							   class="{% if request.resolver_match.kwargs.pk == link.pk %}
										active
									  {% endif %}">
								{{ link.name }}
							</a>
						</li>
					{% endfor %}
				</ul>
		 </div>
        <div class="row my-5">
            <div class="col-6">
                <div class="slider-product text-center">
                  <img src="/media/{{ product.image }}" class="w-50">
                </div>
                <div class="slider-control ml-2 my-3 d-flex text-center">
                  <div class="block">
                    <a href="#"><img src="/media/{{ product.image }}" alt="" class="w-25"></a>
                  </div>
                  <div class="block">
                    <a href="#"><img src="/media/{{ product.image }}" alt="" class="w-25"></a>
                  </div>
                  <div class="block">
                    <a href="#"><img src="/media/{{ product.image }}" alt="" class="w-25"></a>
                  </div>
                </div>
              </div>

              <div class="col-6">
                <h3 class="big-bold">{{ product.name }}</h3>

                <p class="price">{{ product.price }} <span>руб</span></p>
                <a href="{% url 'basket:add' product.pk %}" class="red-button">
                  заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                  {{ product.description }}
                </div>
            </div>
        </div>
    </div>
         <div class="related">
            <div class="title clearfix">
               <h2>Похожие продукты</h2>
               <a class="explore" href="#">показать все <img src="/static/img/arrow.png" alt=""></a>
            </div>
            <div class="related-products clearfix">
                {% for same_prod in same_products%}
               <div class="block">
                  <a href="#"><img src="/media/{{ same_prod.image }}" alt="">
                     <div class="text">
                        <img src="/static/img/icon-hover.png" alt="img">
                      <h4>{{ same_prod.name }}</h4>
                      <p>{{ same_prod.description }} </p>
                     </div>
                  </a>
               </div>
            {% endfor %}

            </div>
         </div>
{% endblock %}

shopkotler/mainapp/templates/mainapp/products.html
{% extends 'shopkotler/base.html' %}
{% load static %}

{% block style %}
	<link rel="stylesheet" type="text/css" href="{% static '/mainapp/style.css' %}">
{% endblock %}

{% block content %}
<!--<div class="" style="padding-left: 98px; padding-right: 211px; position: relative;"></div>-->
	{% include 'shopkotler/includes/inc_products_menu.html' %}

	<div class="details">
		<div class="links clearfix">
			<ul class="links-menu">
				<li>
					<a href="{% url 'products:products' 0 %}"
						class="{% if not request.resolver_match.kwargs.pk %}
									active
								{% endif %}">
						все
					</a>
				</li>

				{% for link in links_menu %}
				<li><a href="{% url 'products:products' pk=link.pk %}" {% if request.resolver_match.kwargs.pk == link.pk %} class="active" {% endif %}>{{link.name}}</a></li>
				{% endfor %}
			</ul>
		</div>

		<div class="details-products">
			<div class="details-slider">
				<div class="slider-product">
					<img src="/media/{{hot_product.image}}">
				</div>
				<div class="slider-control">
					<div class="block">
						<a href="#"><img src="/media/{{hot_product.image}}" style="width: 100px;" alt="">
							<div class="text"></div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="/media/{{hot_product.image}}" style="width: 100px;" alt="">
							<div class="text"></div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="/media/{{hot_product.image}}" style="width: 100px;" alt="">
							<div class="text"></div>
						</a>
					</div>
				</div>
			</div>

			<div class="description">
				<h3 class="big-bold">{{hot_product.name}}</h3>
				<h3 class="red">горячее предложение</h3>
				<p class="price"> {{hot_product.price}} <span>руб</span></p>
				<a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
					заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
				</a>
				<div class="description-text">
					{{hot_product.description}}
				</div>
			</div>
		</div>

		<div>
			{% if category %}
			<h2>Категория: {{ category.name|title }}</h2>
			{% endif %}
		</div>
		<div class="paginator">
			{% if products.has_previous %}
				<a href="{% url 'products:page' category.pk products.previous_page_number %}">
				  <
				</a>
          	{% endif %}
          <span class="current">
            страница {{ products.number }} из
            {{ products.paginator.num_pages }}
          </span>
          	{% if products.has_next %}
				<a href="{% url 'products:page' category.pk products.next_page_number %}">
				  >
				</a>
          	{% endif %}
		</div>
		<div class="products_category">
			{% for product in products %}
				<div class="block w-25 my-3 mx-3">
					<a href="{% url 'basket:add' product.pk %}">
						<img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
						<div class="text">
							<img src="{% static 'img/icon-hover.png' %}" alt="hover">
							<h4>{{ product.name }}</h4>
							<p>{{ product.description }}</p>
						</div>
					</a>
				</div>
			{% endfor %}
		</div>

		<div class="related">
			<div class="title clearfix">
				<h2>Похожие продукты</h2>
				<a class="explore" href="#">показать все <img src="{% static '/img/arrow.png' %}" alt=""></a>
			</div>
			<div class="related-products clearfix">
				<div class="block">
					<a href="#"><img src="{% static '/img/product-11.jpg' %}" alt="">
						<div class="text">
							<img src="{% static '/img/icon-hover.png' %}" alt="img">
							<h4>Стул повышенного качества</h4>
							<p>Не оторваться. </p>
						</div>
					</a>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

